### ISSUE TITLE
Error message in the egs/pretrained_embeddings Tutorial

### ISSUE THREAD

**Issue by kinimod23** [kevinduh/sockeye-recipes#26]
Dear Kevin, thanks for your great work. :)

I am on sockeye version 1.18.72.
When executing...

python3 -m sockeye.init_embedding \
  -w sample-de-en/emb/small.cln.de.vec.npy sample-de-en/emb/small.cln.en.vec.npy \
  -i sample-de-en/emb/small.cln.de.vec.vocab sample-de-en/emb/small.cln.en.vec.vocab \
  -o model/vocab.src.0.json model/vocab.tgt.0.json \
  -n source_embed_weight target_embed_weight \
  -f params.init

...it returns the error message:
sockeye.utils.SockeyeError: Vocabulary sample-de-en/emb/small.cln.de.vec.vocab not valid.

Can you imagine why?

I appreciate your help.
Dominik

**Comment by kinimod23** [comment]
it worked with an earlier sockeye version: 1.18.57

**Comment by kevinduh** [comment]
Hi Dominik, 

The issue was that the new version of sockeye performs a check on the format of the vocabulary file, which our old script wasn't passing (e.g. "<pad>" needs to have id=0). Please pull the latest version of sockeye-recipes 96dc1e9a2bc6e3cad14203b8a0ae87868d2e4297 (which has the updated `scripts/util/vec2npy.py`). That should work! 

Best,
Kevin
